### ISSUE TITLE
Order by "localness" - works, except for Latin America

### ISSUE THREAD

**Issue by joostschouppe** [jbelien/oci-viewer#106]
Nothing mayor, but in general the channels seem to be neatly sorted by how "local" they are (local group > country group > region group > global group). However on the test version at https://oci-viewer.netlify.app/ the Latam channels are on top of the national ones.

**Comment by jbelien** [comment]
Nice catch ! You have the eye of the tiger (or something like that :P)

---

Note for myself: I forgot to handle `level:"subregion"`
