### ISSUE TITLE
Improve UI on mobile

### ISSUE THREAD

**Issue by RobJN** [jbelien/oci-viewer#177]
Currently it is to cramped on small screens.
![Screenshot_20200809-103656](https://user-images.githubusercontent.com/5060210/89728302-a501db80-da2c-11ea-9a97-524fa32c0cbe.png)

**Comment by jbelien** [comment]
![Capture d’écran 2020-08-09 à 12 07 12](https://user-images.githubusercontent.com/1150563/89729739-e6988380-da38-11ea-9b86-2657718161ee.png)

**Comment by RobJN** [comment]
Better but now the results overflow / overlap with the footer. See overlapping text at "United Kingdom"
![Screenshot_20200809-122551](https://user-images.githubusercontent.com/5060210/89730065-ae467480-da3b-11ea-99b5-1872c3728a7b.png)

**Comment by RobJN** [comment]
Thanks for the quick fix.
