### ISSUE TITLE
A map with all communities

### ISSUE THREAD

**Issue by xivk** [jbelien/oci-viewer#19]
Inspired by the missing maps hosts page here

http://www.missingmaps.org/host/#helper-map-contents

You could add a map with all local communities on it and info below.

**Comment by jbelien** [comment]
That's a really cool idea ! 👍

**Comment by jbelien** [comment]
See @mikelmaron demo: https://mikelmaron.github.io/map-demos/osm-community-index/index.html

**Comment by mikelmaron** [comment]
I'd love to see this taken up @jbelien. Had a few ideas on where the demo could go in https://github.com/mikelmaron/map-demos/issues/1

**Comment by jbelien** [comment]
I'm currently working on another project but I'll put this one as next item on my to-do list ! 👍
