### ISSUE TITLE
Add way to link specific territory.

### ISSUE THREAD

**Issue by matkoniecz** [jbelien/oci-viewer#307]
For example, lets say that I welcomed a new user ( like at https://www.openstreetmap.org/changeset/95848279#map=19/50.01753/19.86268&layers=N )

I want to link him list of places where (s)he may ask for help. It would be nice to have way to link to place on map with side panel already opened - right now I would need to add extra instructions about clicking on map to see useful things.

**Comment by jbelien** [comment]
You already have a page per country (example for Belgium : https://community.osm.be/resources/europe/belgium)

But I could indeed add something like `https://community.osm.be/#latlng=50.01753/19.86268` to would display the frontpage (with the map) and the sidebar filled with a "simulated click" on `19.86268, 50.01753` coordinates.
Would that fit your needs ?

**Comment by matkoniecz** [comment]
>  Would that fit your needs ?

yes!

Is it possible to make pages like https://community.osm.be/resources/europe/belgium/ more discoverable? Linkable from bottom of the sidebar panel?
