### ISSUE TITLE
How to add something

### ISSUE THREAD

**Issue by Seandebasti** [jbelien/oci-viewer#410]
Hi, 

thanks for the effort in this!

1. In general I would like to know, how a user can add a new group?
2. Do I have to notice the other original instance of the viewer? means: is that synchron?

I found: [OSM Libya on Facebook](https://www.facebook.com/openstreetmap.libya/)

Thanks

**Comment by jbelien** [comment]
Hello @Seandebasti ,

This is "just" a user interface on top of the [OpenStreetMap Community Index](https://github.com/osmlab/osm-community-index).
You can add a group by editing the OpenStreetMap Community Index (see [CONTRIBUTING.md](https://github.com/osmlab/osm-community-index/blob/main/CONTRIBUTING.md)).

This repository is automatically updated when there is a new release of the OpenStreetMap Community Index so both are always synced.
