### ISSUE TITLE
Expanding to science - geo / carto etc

### ISSUE THREAD

**Issue by Seandebasti** [jbelien/oci-viewer#411]
I really like this community map, 

1. Is there any other community tool which shows the geospatial view on community ranges? 

2. I am interested in having this methodology also implemented for other related fields, such as the associations from cartography (ICACI) to geography and geodesy I have knowledge about, but no sweet map.
It would be nice to compare the geospatial range of different communities.

Interested to contribute?

Thanks

**Comment by jbelien** [comment]
Hello @Seandebasti ,

As explained in other other issue (see https://github.com/jbelien/oci-viewer/issues/410#issuecomment-798439135), this is "just" a user interface on top of the OpenStreetMap Community Index.

I'm not planning to extend it to other "resources" outside the OpenStreetMap Community Index but if you use the same structure as the one used in the OpenStreetMap Community Index (see [schemas](https://github.com/osmlab/osm-community-index/tree/main/schema)), it should be really easy to fork this repo and extend it to whatever you want.

**Comment by Seandebasti** [comment]
Hi @jbelien I like to keep up with my idea. I hope I did understand it right.
First, as Step 1, I should fork the OCI completely and change the categories and add different sources?
Second, as Step 2, I like your viewer. So I should fork it too, afterwards.
First I will try Step 1, then 2 and ask later where the synced linking is described in the source code.
Thirdly, I might get the idea to create a new viewer to connect the OCI resources and my resources to a new one. 
Do you think a sync could be possible?

**Comment by jbelien** [comment]
Yes, I think if you like OCI (and this viewer) but want to extend to non OpenStreetMap related communities/groups, forking both is the easiest solution to start with.
