### ISSUE TITLE
German Telegram Channel

### ISSUE THREAD

**Issue by Discostu36** [jbelien/oci-viewer#435]
The German Telegram Channel https://t.me/OSM_de is now officially called "OSM D-A-CH" and is aimed at users from Germany, Austria and Switzerland. At the moment, oci viewer is only showing the channel for Germany.

**Comment by jbelien** [comment]
Hello @Discostu36 ,

This project is a based on the OpenStreetMap Community Index.
You will have to make that update in the OpenStreetMap Community Index repository : https://github.com/osmlab/osm-community-index
