### ISSUE TITLE
Why is East Midlands in not given the same prominence as Mappa Mercia

### ISSUE THREAD

**Issue by SK53** [jbelien/oci-viewer#464]
The East Midlands OSM community is pretty much, or more, active than Mappa Merica these days. We have been holding regular meetings for over 10 years. Therefore I am puzzled as to why we appear on the map in a much lower contrast to other local groups. If this is just because we don't have a dedicated website or other infrastructure I think it misrepresents what local groups are about.

**Comment by SK53** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/5452818/117451287-3b224e00-af3a-11eb-8d0b-d0a0b7c7576b.png)

I can't find a permalink, but zoom in on Great Britain and East Midlands area is extremely faint. So faint as to be invisible at low zooms. Mappa Mercia are in the West Midlands to the NW of London & East Midlands is a similarly large area to the NE of Mappa Mercia & N of London.

An alternative possibility is that it is something to do with ordering of polygons, but similar issues don't occur for Stuttgart & Baden-Wuerttemburg, where Stuttgarts sits on top of BW which in turn sits on top of Germany. However, in Piemonte, Italy something similar may be happening

**Comment by jbelien** [comment]
Okay, got it!

It's indeed caused by the ordering of the polygons.
I currently do not change any ordering.

But you're right, since "East Midlands (Nottingham) Monthly pub meet-up" appears first in the list (see https://community.osm.be/resources/europe/united_kingdom), it would indeed make sense that it is the most visible.

I'll try to find a way to order polygons according to the list.

**Comment by SK53** [comment]
You could probably use something like OSM Carto does, which is to add a z-order (e.g., local before regional before national with smaller areas before larger ones) and then add an ORDER BY clause when querying the data. I suspect I added East Midlands very early in the existence of the community index. 

Something like :

`ORDER BY CASE group-type WHEN 'local' THEN 1 WHEN 'regional' THEN 2 ELSE 3 END ASC, st_area(geom) DESC`
