### ISSUE TITLE
Update in OSM community index from march not visible

### ISSUE THREAD

**Issue by joostschouppe** [jbelien/oci-viewer#603]
See this edit https://github.com/osmlab/osm-community-index/commit/96bd80205d10272cc3a161a5939e39fd8559693c

**Comment by jbelien** [comment]
Yep, indeed https://community.osm.be/ doesn't seem to update automatically anymore : still "stuck" at version `5.1.2` but OCI is now at version `5.2.0`.

I'll have a look!

**Comment by jbelien** [comment]
It is now fixed! 👍
