### ISSUE TITLE
Use the ordering of resources

### ISSUE THREAD

**Issue by joostschouppe** [jbelien/oci-viewer#61]
Communities can now add their own order their channels as they wish, so it makes sense to reflect this. Details: order - (optional) When several resources with same geography are present, this adjusts the display order (default = 0, higher numbers display more prominently)

**Comment by joostschouppe** [comment]
This is working in the Resources overview, but not in the map view

**Comment by jbelien** [comment]
Oh yes, indeed!

**Comment by jbelien** [comment]
This is fixed in the new version !
It will be closed when new version is released.

**Comment by jbelien** [comment]
New version is released ! 🍾
