### ISSUE TITLE
Add Resource XMPP

### ISSUE THREAD

**Issue by britiger** [jbelien/oci-viewer#98]
XMPP as type of resource was added in osmlab/osm-community-index#347 this should be also added on oci-viewer
I also added a pull request with the first resource: osmlab/osm-community-index#349

**Comment by jbelien** [comment]
oci-viewer is automatically updated with each oci release.
Once your PR is merged and released, your XMPP resource should be automatically added to oci-viewer.

Let me know if it's not the case !

**Comment by jbelien** [comment]
I added XMPP in the filter listbox in the main page.
